version: "3"
services:
  conflictvisualizer-gui:
    build:
      context: gui
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        MAPBOX_TOKEN: ${MAPBOX_TOKEN}
        GUI_SERVER_URL: ${GUI_SERVER_URL}
        AUTH_SERVER_URL: ${AUTH_SERVER_URL}
        API_SERVER_URL: ${API_SERVER_URL}
    ports:
      - "3000:3000"
    image: jpo-conflictvisualizer-gui:latest
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  keycloak:
    container_name: jpo-conflictvisualizer-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      GUI_SERVER_URL: ${GUI_SERVER_URL}
      API_SERVER_URL: ${API_SERVER_URL}
    command:
      - start-dev
      - --log-level=INFO
      - --import-realm
    image: quay.io/keycloak/keycloak
    volumes:
      - ${DOCKER_HOST_DIR}/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8084:8080"

  conflictvisualizer-api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: jpo-conflictvisualizer-api:latest
    environment:
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_HOST_IP: ${DB_HOST_IP}
      DB_HOST_PORT: ${DB_HOST_PORT}
      SPRING_KAFKA_BOOTSTRAPSERVERS: ${KAFKA_BROKER_IP}:${KAFKA_BROKER_PORT}
      load: "false"
      #KAFKA_BROKER_IP: ${KAFKA_BROKER_IP}
      #KAFKA_BROKER_PORT: ${KAFKA_BROKER_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
