version: "3"
services:
  conflictvisualizer-gui:
    build: 
      context: gui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: jpo-conflictvisualizer-gui:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    # networks:
    #   - conflictmonitor

  keycloak:
    container_name: jpo-conflictvisualizer-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: 
      - start-dev
      - --log-level=INFO
      - --import-realm
    image: quay.io/keycloak/keycloak
    volumes:
      - ${DOCKER_HOST_DIR}/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8084:8080"
    # networks:
    #   - conflictmonitor

  conflictvisualizer-api:
    build: 
      context: api 
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    image: jpo-conflictvisualizer-api:latest
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    # networks:
    #   - conflictmonitor

# networks:
#   conflictmonitor:
#     name: conflictmonitor_network
#     external: true
